[project]
name = "Heuristics Selector"
version = "0.1.0"
description = "My demo selector"
authors = [{ name = "John Doe", email = "john.doe@composabl.com" }]
dependencies = [
    "composabl-core"
]

[composabl]
type = "selector-controller"
entrypoint = "programmed_selector.controller:Controller"
